# Generated by Django 5.0.6 on 2024-09-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maridaje_App', '0002_maridaje_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='comida',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='comidas/'),
        ),
        migrations.AddField(
            model_name='vino',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='vinos/'),
        ),
    ]
